/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 15 18:52:21 GMT 2017
 */

package finalprojectB;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import finalprojectB.DomainValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DomainValidator_ESTest extends DomainValidator_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      boolean boolean0 = domainValidator0.isValidLocalTld("localhost");
      assertFalse(boolean0);
  }

  @Test
  public void test01()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidInfrastructureTld("root");
      assertTrue(boolean0);
  }

  @Test
  public void test02()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      boolean boolean0 = domainValidator0.isValidInfrastructureTld("Lfa)4.\"{(-Q!1DbI6Q.");
      assertFalse(boolean0);
  }

  @Test
  public void test03()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      boolean boolean0 = domainValidator0.isValidGenericTld("name");
      assertTrue(boolean0);
  }

  @Test
  public void test04()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidCountryCodeTld("cg");
      assertTrue(boolean0);
  }

  @Test
  public void test05()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidCountryCodeTld("");
      assertFalse(boolean0);
  }

  @Test
  public void test06()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      // Undeclared exception!
      try { 
        domainValidator0.isValidTld((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("finalprojectB.DomainValidator", e);
      }
  }

  @Test
  public void test07()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      // Undeclared exception!
      try { 
        domainValidator0.isValidLocalTld((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("finalprojectB.DomainValidator", e);
      }
  }

  @Test
  public void test08()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      // Undeclared exception!
      try { 
        domainValidator0.isValidInfrastructureTld((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("finalprojectB.DomainValidator", e);
      }
  }

  @Test
  public void test09()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      // Undeclared exception!
      try { 
        domainValidator0.isValidGenericTld((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("finalprojectB.DomainValidator", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      // Undeclared exception!
      try { 
        domainValidator0.isValidCountryCodeTld((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("finalprojectB.DomainValidator", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidTld("fm");
      assertTrue(boolean0);
  }

  @Test
  public void test12()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidTld("root");
      assertTrue(boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      boolean boolean0 = domainValidator0.isValidTld("localhost");
      assertFalse(boolean0);
  }

  @Test
  public void test14()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      boolean boolean0 = domainValidator0.isValid("Millisecond");
      assertFalse(boolean0);
  }

  @Test
  public void test15()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      boolean boolean0 = domainValidator0.isValidTld("]$pVZ,CcgK");
      assertTrue(boolean0);
  }

  @Test
  public void test16()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValid("org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl");
      assertFalse(boolean0);
  }

  @Test
  public void test17()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValid("");
      assertFalse(boolean0);
  }

  @Test
  public void test18()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(false);
      boolean boolean0 = domainValidator0.isValidTld("aero");
      assertTrue(boolean0);
  }

  @Test
  public void test19()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance(true);
      boolean boolean0 = domainValidator0.isValid("");
      assertTrue(boolean0);
  }

  @Test
  public void test20()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidGenericTld(".to\"0b[isE6");
      assertFalse(boolean0);
  }

  @Test
  public void test21()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance();
      boolean boolean0 = domainValidator0.isValidLocalTld("]$pVZ,CcgK");
      assertTrue(boolean0);
  }
}
