/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 15 18:53:27 GMT 2017
 */

package finalprojectB;

import org.junit.Test;
import static org.junit.Assert.*;
import finalprojectB.ResultPair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ResultPair_ESTest extends ResultPair_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ResultPair resultPair0 = new ResultPair("", true);
      assertTrue(resultPair0.valid);
  }
}
